const fs = require('fs');
const path = require('path');
const assert = require('assert');

const root = path.join(__dirname,'..');
const route = fs.readFileSync(path.join(root,'routes/agente_financeiro_drive.js'),'utf8');
const start = fs.readFileSync(path.join(root,'scripts/start.js'),'utf8');
const page = fs.readFileSync(path.join(root,'public/agente-financeiro-semanal.html'),'utf8');
const importPage = fs.readFileSync(path.join(root,'public/agente-financeiro-importacao.html'),'utf8');

assert.match(route,/drive\.readonly/);
assert.match(route,/GOOGLE_DRIVE_SERVICE_ACCOUNT_EMAIL/);
assert.match(route,/GOOGLE_DRIVE_PRIVATE_KEY/);
assert.match(route,/GOOGLE_DRIVE_FATURAS_FOLDER_ID/);
assert.match(route,/CARTAO_PDF_PASSWORD/);
assert.match(route,/normalizarFolderId/);
assert.match(route,/supportsAllDrives/);
assert.match(route,/includeItemsFromAllDrives/);
assert.match(route,/listarVisiveis/);
assert.match(route,/varredura_visiveis/);
assert.match(route,/tentarMetadataPasta/);
assert.match(route,/contaServico/);
assert.match(route,/pastaConfiguradaId/);
assert.match(route,/itensEncontrados/);
assert.match(route,/candidatosFaturaVisiveis/);
assert.match(route,/\[Agente Financeiro\]\[Drive\]/);
assert.match(route,/r\.get\('\/status'/);
assert.match(route,/r\.get\('\/arquivos'/);
assert.match(route,/r\.post\('\/extrair'/);
assert.match(route,/r\.post\('\/interpretar'/);
assert.match(route,/r\.post\('\/importar'/);
assert.match(route,/DIVERGENCIA_TOTAL/);
assert.match(route,/FATURA_EXISTENTE/);
assert.match(route,/protegerPoolPorLoja/);
assert.match(start,/\/api\/agente-financeiro\/drive/);
assert.match(page,/drive\/status/);
assert.match(page,/drive\/arquivos/);
assert.match(importPage,/drive\/interpretar/);
assert.match(importPage,/drive\/importar/);
console.log('agente-financeiro-drive.test.js: OK');
